spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  sql:
    init:
      mode: never
  data:
    redis:
      host: redis
      port: 6379
      database: 0
