spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://192.168.168.128:3306/mianshitong?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:123456}
  sql:
    init:
      mode: always
      encoding: UTF-8
  data:
    redis:
      host: ${REDIS_HOST:192.168.168.128}
      port: ${REDIS_PORT:6379}
      database: 0
